[build-system]
requires = [
    "setuptools==80.9.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "docassemble.MAObjectionToEvictionPetition"
version = "1.1"
description = "Objection to petition in an eviction action"
readme = "README.md"
authors = [
    { name = "Suffolk LIT Lab", email = "litlab@suffolk.edu" },
]
dependencies = [
    "docassemble.ALMassachusetts @ git+https://github.com/SuffolkLITLab/docassemble-ALMassachusetts.git@main",
    "docassemble.AssemblyLine @ git+https://github.com/SuffolkLITLab/docassemble-AssemblyLine.git@main",
]

[project.urls]
Homepage = "https://courtformsonline.org"

[tool.setuptools.packages.find]
where = [
    ".",
]
